baseURL = "https://new.vinagro.sk"
languageCode = "sk-sk"
title = "Vinagro a.s."
themesDir = "themes"
theme = "hero"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Hugo Hero"

  [params.homepage_meta_tags]
    meta_description = "Vinagro a.s. - zemedělská prvovýroba a poskytoval služeb v zemědělství"
    meta_og_title = "Vinagro a.s."
    meta_og_type = "website"
    meta_og_url = "https://www.vinagro.sk"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Vinagro a.s. - zemedělská prvovýroba a poskytoval služeb v zemědělství"
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
	name = "Služby"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "O nás"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Historie"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Kontakty"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
